export const classes = [
  {
  name: "Warior",
  abv:  "WAR",
  disc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mattis ornare imperdiet. Mauris tincidunt lobortis risus at eleifend. Aliquam ornare erat sed nulla pretium, vehicula iaculis lacus suscipit. Cras egestas imperdiet est sit amet luctus. Nam tempus nulla vitae nibh pretium, sit amet iaculis turpis consectetur. Nam vitae lacus elementum, suscipit quam rhoncus, consectetur nisl. Cras lacus ex, lobortis sit amet egestas at, luctus at nulla. Integer venenatis neque sit amet mi ullamcorper malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Nam ultrices, turpis nec pellentesque ultricies, dui eros aliquam urna, nec porttitor lacus magna et orci. Vivamus vitae tempor libero, sed mollis tellus. Maecenas consectetur scelerisque ex sed mattis. Donec porttitor ut nibh at varius. Proin vulputate elementum tellus, dictum lobortis felis hendrerit eu. Proin fermentum, odio at elementum feugiat, lorem dui lacinia dolor, sit amet convallis mauris felis vitae nisi. Integer risus quam, imperdiet vitae fermentum eu, facilisis nec massa. Curabitur egestas consequat magna, in dapibus eros placerat non. Cras eget est at justo varius suscipit. Donec porttitor dapibus magna, sed tincidunt nisl semper vitae. Pellentesque nec nisl quis dolor tincidunt consequat pulvinar a nisi. Suspendisse tempor tempor nunc, quis bibendum ligula lobortis eget. In at dictum orci. Curabitur sed odio id ante efficitur malesuada. Suspendisse sed ipsum enim. Vestibulum congue nunc ac facilisis porttitor. Sed quis nisi quis urna rhoncus molestie. Nunc ornare a eros et ultrices. Mauris nec sollicitudin tellus."
  },
  {
    name: "Hunter",
    abv:  "HUN",
    dis: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mattis ornare imperdiet. Mauris tincidunt lobortis risus at eleifend. Aliquam ornare erat sed nulla pretium, vehicula iaculis lacus suscipit. Cras egestas imperdiet est sit amet luctus. Nam tempus nulla vitae nibh pretium, sit amet iaculis turpis consectetur. Nam vitae lacus elementum, suscipit quam rhoncus, consectetur nisl. Cras lacus ex, lobortis sit amet egestas at, luctus at nulla. Integer venenatis neque sit amet mi ullamcorper malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Nam ultrices, turpis nec pellentesque ultricies, dui eros aliquam urna, nec porttitor lacus magna et orci. Vivamus vitae tempor libero, sed mollis tellus. Maecenas consectetur scelerisque ex sed mattis. Donec porttitor ut nibh at varius. Proin vulputate elementum tellus, dictum lobortis felis hendrerit eu. Proin fermentum, odio at elementum feugiat, lorem dui lacinia dolor, sit amet convallis mauris felis vitae nisi. Integer risus quam, imperdiet vitae fermentum eu, facilisis nec massa. Curabitur egestas consequat magna, in dapibus eros placerat non. Cras eget est at justo varius suscipit. Donec porttitor dapibus magna, sed tincidunt nisl semper vitae. Pellentesque nec nisl quis dolor tincidunt consequat pulvinar a nisi. Suspendisse tempor tempor nunc, quis bibendum ligula lobortis eget. In at dictum orci. Curabitur sed odio id ante efficitur malesuada. Suspendisse sed ipsum enim. Vestibulum congue nunc ac facilisis porttitor. Sed quis nisi quis urna rhoncus molestie. Nunc ornare a eros et ultrices. Mauris nec sollicitudin tellus.",
  },
  {
    name: "Healer",
    abv:  "HEA",
    dis: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis mattis ornare imperdiet. Mauris tincidunt lobortis risus at eleifend. Aliquam ornare erat sed nulla pretium, vehicula iaculis lacus suscipit. Cras egestas imperdiet est sit amet luctus. Nam tempus nulla vitae nibh pretium, sit amet iaculis turpis consectetur. Nam vitae lacus elementum, suscipit quam rhoncus, consectetur nisl. Cras lacus ex, lobortis sit amet egestas at, luctus at nulla. Integer venenatis neque sit amet mi ullamcorper malesuada. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Nam ultrices, turpis nec pellentesque ultricies, dui eros aliquam urna, nec porttitor lacus magna et orci. Vivamus vitae tempor libero, sed mollis tellus. Maecenas consectetur scelerisque ex sed mattis. Donec porttitor ut nibh at varius. Proin vulputate elementum tellus, dictum lobortis felis hendrerit eu. Proin fermentum, odio at elementum feugiat, lorem dui lacinia dolor, sit amet convallis mauris felis vitae nisi. Integer risus quam, imperdiet vitae fermentum eu, facilisis nec massa. Curabitur egestas consequat magna, in dapibus eros placerat non. Cras eget est at justo varius suscipit. Donec porttitor dapibus magna, sed tincidunt nisl semper vitae. Pellentesque nec nisl quis dolor tincidunt consequat pulvinar a nisi. Suspendisse tempor tempor nunc, quis bibendum ligula lobortis eget. In at dictum orci. Curabitur sed odio id ante efficitur malesuada. Suspendisse sed ipsum enim. Vestibulum congue nunc ac facilisis porttitor. Sed quis nisi quis urna rhoncus molestie. Nunc ornare a eros et ultrices. Mauris nec sollicitudin tellus.",
  }
];